version: 2
updates:
  - package-ecosystem: "bun"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "main"
    assignees:
      - "ukwhatn"
    groups:
      dev-dependencies:
        dependency-type: "development"
      testing:
        patterns:
          - "@types/*"
      linting:
        patterns:
          - "@biomejs/*"
          - "typescript"
    cooldown:
      default-days: 3
      semver-patch-days: 1
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "main"
    assignees:
      - "ukwhatn"
    groups:
      github-actions:
        patterns:
          - "*"
